### ISSUE TITLE
PHP > Fatal error sur fetch_all()

### ISSUE THREAD

**Issue by thomascerdan** [OuestFrance-Multimedia/Google-Search-Console-Archive#5]
Bonjour,
En voulant essayer d'installer votre script sur mon environnement je rencontre un problème.
J'ai (normalement) bien suivi toutes les instructions : la connexion à la Search Console se fait sans problème, les données s'insèrent bien dans la BDD, jusqu'ici tout va bien !

Lorsque j'essaie de restituer les données en accédant à /index.php, j'ai en revanche une erreur PHP qui remonte : 

`Fatal error: Call to undefined method mysqli_result::fetch_all() in /*/models/database.php on line 534`

J'utilise pourtant la version 5.6 de PHP, donc il ne devrait pas y avoir de problème de compatibilité, peut-être un problème lié à des types de variables ? Je suis plutôt débutant sur PHP, je vais essayer de creuser de mon côté mais si jamais vous avez la solution cela me serait d'une grande utilité.

Merci par avance,

**Comment by zodman** [comment]
the answer:

https://stackoverflow.com/a/26497866

invalid issue!

**Comment by thomascerdan** [comment]
It worked ! Thank you for posting the answer.
